[package]
name = "hearth-web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
hearth-ui = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]

